name: Deploy to EC2

on:
  push:
    branches:
      - master

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  DOCKER_COMPOSE_PATH: /root/payment-error-cicd
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_USERNAME: ${{ secrets.EC2_USERNAME }}
  SSH_HOST: ${{ secrets.EC2_SSH_HOST }}
  SSH_PORT: 22

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_HUB_USERNAME }}
        password: ${{ env.DOCKER_HUB_PASSWORD }}
    - name: Build Docker image
      run: |
        docker build -t moveho/payment:latest .
        docker push moveho/payment:latest        
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2    
      with:
        key: ${{ env.SSH_PRIVATE_KEY }}
        name: ssh-key 
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        command: |
          cd $DOCKER_COMPOSE_PATH
          docker-compose down
          docker-compose pull
          docker-compose up -d
        host: ${{ env.SSH_HOST }}
        username: ${{ env.SSH_USERNAME }}
        port: ${{ env.SSH_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: $HOME/.ssh/known_hosts
