name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t moveho/payment:${{ github.sha }} .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push moveho/payment:${{ github.sha }}

    - name: SSH into EC2 instance and pull latest image
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.SSH_USERNAME }}
        host: ${{ secrets.SSH_HOST }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull moveho/payment:${{ github.sha }}
          docker stop payment || true
          docker rm payment || true
          docker run -d --name payment -p 80:80 moveho/payment:${{ github.sha }}
