name: Update Docker container on VM

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: moveho/payment:latest

    - name: SSH into VM and update Docker container
      uses: appleboy/ssh-action/ssh-deploy@v1.1.2
      with:
        host: example.com
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /home/kevin/payment-error-cicd
          docker-compose down
          docker-compose pull
          docker-compose up -d
